version: "3.9"

services:
  nifi:
    image: apache/nifi:${NIFI_VERSION}
    container_name: ${NIFI_NAME}
    ports:
      - "${NIFI_HOST_PORT}:${NIFI_PORT}"
    environment:
      NIFI_WEB_HTTPS_PORT: ${NIFI_PORT}
      SINGLE_USER_CREDENTIALS_USERNAME: ${NIFI_USERNAME}
      SINGLE_USER_CREDENTIALS_PASSWORD: ${NIFI_PASSWORD}
      NIFI_SENSITIVE_PROPS_KEY: ${NIFI_KEY}
      NIFI_JVM_HEAP_INIT: ${NIFI_MEM_MIN}
      NIFI_JVM_HEAP_MAX: ${NIFI_MEM_MAX}
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_database:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_lib:/opt/nifi/nifi-current/lib
    networks:
      - bw_net
  
  registry:
    image: apache/nifi-registry:${NIFI_REGISTRY_VERSION}
    container_name: ${NIFI_REGISTRY_NAME}
    ports:
      - "${NIFI_REGISTRY_HOST_PORT}:${NIFI_REGISTRY_PORT}"
    volumes:
      - registry_data:/opt/nifi-registry/nifi-registry-current
    networks:
      - bw_net


networks:
  bw_net:
    driver: bridge

volumes:
  nifi_conf:
  nifi_state:
  nifi_database:
  nifi_flowfile:
  nifi_content:
  nifi_provenance:
  nifi_logs:
  nifi_lib:
  registry_data: